name: Deploy HTML to EC2

on:
  push:
    branches:
      - master # CHANGE 1: Aapki branch 'master' hai, 'main' nahi

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # 1. Files ko Server pe Copy karo (SCP)
      - name: Copy files via SSH
        uses: appleboy/scp-action@master
        with:
          # CHANGE 2: 'secrets.' keyword add kiya hai sab jagah
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "."
          target: "/home/ubuntu/project"

      # 2. Server pe Script Run karo (SSH)
      - name: Execute Deploy Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Script chalao jo files ko sahi jagah move karegi
            bash /home/ubuntu/my.sh
